sudo: false
language: rust
cache: cargo

os:
    - linux
    - osx

rust:
    - stable
    - beta
    - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

services:
  - redis-server

addons:
  homebrew:
    packages: redis
    update: true

script:
  - cargo build --verbose --all
  - cargo test --verbose --all -- --test-threads=1
